import { Metadata } from 'next';
import { createOgMetadata } from '@/lib/og/create-og-metadata';
import SectionWrapper from '@/components/ui/SectionWrapper';

export const metadata: Metadata = {
  title: 'Terms of Service | Ambr',
  description: 'Terms of Service for the Ambr Protocol platform.',
  ...createOgMetadata({
    title: 'Terms of Service | Ambr',
    description: 'Terms of Service for the Ambr Protocol platform.',
    path: '/terms',
    label: 'Legal',
    domain: 'ambr.run',
  }),
};

export default function TermsPage() {
  return (
    <main>
      <SectionWrapper>
        <div className="mx-auto max-w-3xl prose-invert">
          <h1 className="text-3xl text-text-primary mb-6">Terms of Service</h1>
          <p className="text-sm text-text-secondary mb-8">Last updated: March 9, 2026</p>

          <div className="space-y-6 text-sm text-text-secondary leading-relaxed">
            <section>
              <h2 className="text-lg text-text-primary mb-2">1. Acceptance of Terms</h2>
              <p>
                By accessing or using the Ambr website, API, or any related services
                (collectively, the &quot;Service&quot;), you agree to be bound by these Terms of
                Service. If you do not agree, do not use the Service.
              </p>
            </section>

            <section>
              <h2 className="text-lg text-text-primary mb-2">2. Service Description</h2>
              <p>
                Ambr is a contract generation and verification platform. We provide
                AI-powered tools for creating dual-format contracts (human-readable and
                machine-parsable) from structured, jurisdiction-aware templates. The Service
                includes contract generation via API, hash-based verification, a contract
                reader portal, and export functionality.
              </p>
              <p className="mt-2 font-medium text-amber">
                Ambr is NOT a law firm. We do NOT provide legal advice, legal
                representation, or legal document review. We do NOT review generated contracts
                for legal sufficiency.
              </p>
            </section>

            <section>
              <h2 className="text-lg text-text-primary mb-2">3. Not Legal Advice</h2>
              <p>
                Contracts generated by Ambr are produced by artificial intelligence
                from template structures informed by legal research. Generated contracts have
                NOT been reviewed by an attorney. The inclusion of jurisdiction-specific
                references (e.g., eIDAS, UETA) in templates does not constitute
                legal certification of the generated output.
              </p>
              <p className="mt-2">
                You should consult qualified legal counsel in your jurisdiction before relying
                on, executing, or distributing any contract generated through the Service.
                Ambr does not guarantee the legal enforceability, validity, or
                completeness of generated contracts in any jurisdiction.
              </p>
            </section>

            <section>
              <h2 className="text-lg text-text-primary mb-2">4. AI-Generated Content</h2>
              <p>
                Contracts are generated using large language models. While templates incorporate
                jurisdiction-specific legal research informing their structure, AI-generated
                output may contain errors, omissions, or inaccuracies. You are solely
                responsible for reviewing all generated contracts before use. Ambr
                does not warrant the accuracy, completeness, or fitness for purpose of any
                AI-generated content.
              </p>
            </section>

            <section>
              <h2 className="text-lg text-text-primary mb-2">5. Account and API Keys</h2>
              <p>
                API keys are personal, non-transferable, and issued to a single email address.
                You are responsible for safeguarding your API key. Ambr may revoke
                API keys at any time for violations of these Terms, suspected abuse, or
                security concerns. API keys cannot be recovered once lost.
              </p>
            </section>

            <section>
              <h2 className="text-lg text-text-primary mb-2">6. Payment Terms</h2>
              <p>
                API access requires payment in USDC on the Base L2 network to the designated
                wallet address. Credits are non-refundable and non-transferable. Credit
                balances do not expire but may be adjusted if pricing tiers change. Enterprise
                tier (&quot;unlimited&quot;) credits are subject to fair-use policies.
              </p>
            </section>

            <section>
              <h2 className="text-lg text-text-primary mb-2">7. Intellectual Property</h2>
              <p>
                Contracts generated through the Service belong to you (the user or the
                principal identified in the contract). The Ambr platform, including
                its templates, source code, API, branding, and documentation, remains the
                intellectual property of Ambr. Template structures may not be
                extracted, reverse-engineered, or redistributed.
              </p>
            </section>

            <section>
              <h2 className="text-lg text-text-primary mb-2">8. Hash Verification</h2>
              <p>
                SHA-256 hash verification provided by the Service confirms technical integrity
                — that a contract has not been modified since its creation. Hash verification
                does NOT constitute legal certification, notarization, authentication of
                identity, or validation of contract terms. The &quot;Hash Verified&quot; status
                indicates only that the document matches its original cryptographic fingerprint.
              </p>
            </section>

            <section>
              <h2 className="text-lg text-text-primary mb-2">9. Dispute Resolution</h2>
              <p>
                Contracts generated through Ambr may include IETF Agentic Dispute
                Protocol (ADP) clauses for dispute resolution between contracting parties.
                Ambr is not a party to any contract generated through the Service
                and bears no responsibility for disputes between contracting parties.
              </p>
              <p className="mt-2">
                Any disputes between you and Ambr relating to the Service shall be
                governed by the laws of the State of Delaware, without regard to conflict of
                law provisions.
              </p>
            </section>

            <section>
              <h2 className="text-lg text-text-primary mb-2">10. Limitation of Liability</h2>
              <p>
                The Service is provided &quot;AS IS&quot; and &quot;AS AVAILABLE&quot; without
                warranties of any kind, express or implied. Ambr disclaims all
                warranties including merchantability, fitness for a particular purpose, and
                non-infringement.
              </p>
              <p className="mt-2">
                In no event shall Ambr be liable for any indirect, incidental,
                special, consequential, or punitive damages arising from your use of the
                Service, including but not limited to reliance on generated contracts,
                business losses, or legal disputes. Total liability is capped at the fees
                paid by you in the twelve (12) months preceding the claim.
              </p>
            </section>

            <section>
              <h2 className="text-lg text-text-primary mb-2">11. Termination</h2>
              <p>
                Ambr may suspend or terminate your access to the Service, including
                revocation of API keys, at any time and for any reason, including violation
                of these Terms, suspected abuse, or conduct that may harm other users or the
                platform. Unused credits are not refundable upon termination for cause.
              </p>
            </section>

            <section>
              <h2 className="text-lg text-text-primary mb-2">12. Contact</h2>
              <p>
                For questions about these Terms, contact us at{' '}
                <a href="mailto:hello@ambr.run" className="text-amber hover:underline">
                  hello@ambr.run
                </a>.
              </p>
            </section>
          </div>
        </div>
      </SectionWrapper>
    </main>
  );
}
