import { Metadata } from 'next';
import { createOgMetadata } from '@/lib/og/create-og-metadata';
import SectionWrapper from '@/components/ui/SectionWrapper';

export const metadata: Metadata = {
  title: 'Privacy Policy | Ambr',
  description: 'Privacy Policy for the Ambr Protocol platform.',
  ...createOgMetadata({
    title: 'Privacy Policy | Ambr',
    description: 'Privacy Policy for the Ambr Protocol platform.',
    path: '/privacy',
    label: 'Legal',
    domain: 'ambr.run',
  }),
};

export default function PrivacyPage() {
  return (
    <main>
      <SectionWrapper>
        <div className="mx-auto max-w-3xl prose-invert">
          <h1 className="text-3xl text-text-primary mb-6">Privacy Policy</h1>
          <p className="text-sm text-text-secondary mb-8">Last updated: March 11, 2026</p>

          <div className="space-y-6 text-sm text-text-secondary leading-relaxed">
            <section>
              <h2 className="text-lg text-text-primary mb-2">1. Information We Collect</h2>
              <p className="mb-3">
                <span className="font-medium text-text-primary">Waitlist:</span> Email address, and optionally your name, role, and message.
              </p>
              <p className="mb-3">
                <span className="font-medium text-text-primary">API Keys:</span> Email address associated with your API key. API keys are stored as SHA-256 hashes — we cannot recover the original key.
              </p>
              <p className="mb-3">
                <span className="font-medium text-text-primary">Contracts:</span> When you create a Ricardian Contract, we store the contract text (human-readable and machine-readable JSON), SHA-256 hash, principal declaration (agent ID, principal name, principal type), and creation metadata.
              </p>
              <p className="mb-3">
                <span className="font-medium text-text-primary">Signatures:</span> Wallet addresses and ECDSA signatures submitted when signing contracts.
              </p>
              <p>
                <span className="font-medium text-text-primary">Share Tokens:</span> When you generate a share link, we store the token, associated contract, and expiry date.
              </p>
            </section>

            <section>
              <h2 className="text-lg text-text-primary mb-2">2. Lawful Basis for Processing</h2>
              <p className="mb-3">
                Under the EU General Data Protection Regulation (GDPR), we process personal data on the following bases:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>
                  <span className="font-medium text-text-primary">Contract performance (Art. 6(1)(b)):</span> Processing contract data, signatures, and principal declarations is necessary to perform the service you requested — creating, signing, and verifying Ricardian Contracts.
                </li>
                <li>
                  <span className="font-medium text-text-primary">Legitimate interest (Art. 6(1)(f)):</span> Hash verification and contract metadata (contract ID, status, dates) are publicly accessible to enable document integrity verification. This serves the legitimate interest of all contract parties and third-party verifiers.
                </li>
                <li>
                  <span className="font-medium text-text-primary">Consent (Art. 6(1)(a)):</span> Waitlist subscriptions and marketing communications are based on your explicit consent.
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg text-text-primary mb-2">3. Contract Visibility</h2>
              <p className="mb-3">
                Ambr follows a <span className="font-medium text-text-primary">private-by-default</span> model for contract data:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>
                  <span className="font-medium text-text-primary">Public (no authentication):</span> Contract metadata only — contract ID, status, SHA-256 hash, amendment type, and creation date. This enables hash verification without exposing contract content.
                </li>
                <li>
                  <span className="font-medium text-text-primary">Private (authentication required):</span> Full contract text, principal declarations, and financial terms require either: (a) the API key of the contract creator, or (b) a valid share token generated by a contract party.
                </li>
                <li>
                  <span className="font-medium text-text-primary">Shared (consent-based):</span> Contract parties can generate time-limited share links to grant read access to lawyers, auditors, or counterparties.
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg text-text-primary mb-2">4. Data Storage and Security</h2>
              <p>
                Your data is stored securely using Supabase with row-level security policies.
                Data is encrypted in transit (TLS) and at rest. API keys are stored as irreversible
                SHA-256 hashes. Share tokens expire automatically and are validated server-side
                using a service-role client (not accessible via public APIs).
              </p>
            </section>

            <section>
              <h2 className="text-lg text-text-primary mb-2">5. Data Minimization</h2>
              <p>
                We collect only data necessary to provide the service. Public-facing views
                expose only metadata (no personal data). Share tokens are ephemeral with
                configurable expiry (default: 7 days, maximum: 1 year).
              </p>
            </section>

            <section>
              <h2 className="text-lg text-text-primary mb-2">6. Your Rights</h2>
              <p className="mb-3">Under GDPR, you have the right to:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li><span className="font-medium text-text-primary">Access:</span> Request a copy of all personal data we hold about you.</li>
                <li><span className="font-medium text-text-primary">Rectification:</span> Request correction of inaccurate data.</li>
                <li>
                  <span className="font-medium text-text-primary">Erasure:</span> Request deletion of your data. For contracts, this means
                  the human-readable text and principal declaration will be replaced with
                  &quot;[REDACTED]&quot;. The SHA-256 hash is preserved to maintain chain integrity for
                  other parties and amendments, but no personal data remains in the hash
                  (it is a one-way function).
                </li>
                <li><span className="font-medium text-text-primary">Portability:</span> Export your contracts in JSON, Markdown, or plain text format via the API or Reader Portal.</li>
                <li><span className="font-medium text-text-primary">Objection:</span> Object to processing based on legitimate interest.</li>
              </ul>
              <p className="mt-3">We will respond to all requests within 30 days.</p>
            </section>

            <section>
              <h2 className="text-lg text-text-primary mb-2">7. Third Parties</h2>
              <p>
                We do not sell or share your personal information with third parties.
                Contract data is processed using Anthropic&apos;s Claude API for AI-generated
                contract text — Anthropic does not retain API inputs/outputs for training
                purposes.
              </p>
            </section>

            <section>
              <h2 className="text-lg text-text-primary mb-2">8. Contact</h2>
              <p>
                For privacy-related inquiries, data access requests, or erasure requests,
                contact us at privacy@ambr.run.
              </p>
            </section>
          </div>
        </div>
      </SectionWrapper>
    </main>
  );
}
